# Generated by Django 5.2 on 2026-01-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
