# Generated by Django 5.2 on 2026-01-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('size', models.CharField(max_length=20)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
