# Generated by Django 5.2 on 2026-01-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
